# .air.toml
# Pastikan file ini di root project

[build]
cmd = "go run ./cmd/main.go"
bin = "tmp/main"
full_bin = "false"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp", "node_modules"]
delay = 1000
stop_on_error = true
